// Code generated by warchest; DO NOT EDIT.
// source: schedule.warchest

//go:generate go tool warchest generate

package schedule

import (
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
	"time"

	. "warchest/wc"
)

// ParseForm validates raw form input into an Event. The error type names
// the only failure mode this can produce, and each `?` below propagates it.
func ParseForm(name, startDate, days, startHour, endHour string) Result[Event, ValidationError] {
	trimmed := strings.TrimSpace(name)
	if trimmed == "" {
		return Err[Event](ValidationError{Field: "name", Msg: "give the event a name"})
	}
	if _, err := time.Parse("2006-01-02", strings.TrimSpace(startDate)); err != nil {
		return Err[Event](ValidationError{Field: "start date", Msg: "use YYYY-MM-DD"})
	}
	__r0 := parseRange(days, "days", 1, 14)
	if __r0.IsErr() {
		return Err[Event](__r0.UnwrapErr())
	}
	d := __r0.Unwrap()
	__r1 := parseRange(startHour, "start hour", 0, 23)
	if __r1.IsErr() {
		return Err[Event](__r1.UnwrapErr())
	}
	sh := __r1.Unwrap()
	__r2 := parseRange(endHour, "end hour", 1, 24)
	if __r2.IsErr() {
		return Err[Event](__r2.UnwrapErr())
	}
	eh := __r2.Unwrap()
	if eh <= sh {
		return Err[Event](ValidationError{Field: "end hour", Msg: "must be after the start hour"})
	}
	return Ok[Event, ValidationError](Event{
		Name:      trimmed,
		StartDate: strings.TrimSpace(startDate),
		Days:      d,
		StartHour: sh,
		EndHour:   eh,
	})
}

func parseRange(s, field string, lo, hi int) Result[int, ValidationError] {
	n, err := strconv.Atoi(strings.TrimSpace(s))
	if err != nil {
		return Err[int](ValidationError{Field: field, Msg: "not a number"})
	}
	if n < lo || n > hi {
		return Err[int](ValidationError{Field: field, Msg: fmt.Sprintf("must be between %d and %d", lo, hi)})
	}
	return Ok[int, ValidationError](n)
}

// DayLabels formats each day of the event, e.g. "Mon 6/15".
func DayLabels(e Event) Result[[]string, error] {
	__v0, __err0 := time.Parse("2006-01-02", e.StartDate)
	if __err0 != nil {
		return Err[[]string](__err0)
	}
	start := __v0
	labels := make([]string, e.Days)
	for i := range labels {
		labels[i] = start.AddDate(0, 0, i).Format("Mon 1/2")
	}
	return Ok[[]string, error](labels)
}

// Encode serializes an event for storage.
func Encode(e Event) Result[string, error] {
	__v0, __err0 := json.Marshal(e)
	if __err0 != nil {
		return Err[string](__err0)
	}
	b := __v0
	return Ok[string, error](string(b))
}

// Decode parses a stored event.
func Decode(s string) Result[Event, error] {
	var e Event
	if err := json.Unmarshal([]byte(s), &e); err != nil {
		return Err[Event](err)
	}
	return Ok[Event, error](e)
}

// EncodeAll serializes a whole workspace of events keyed by id.
func EncodeAll(events map[string]Event) Result[string, error] {
	__v0, __err0 := json.Marshal(events)
	if __err0 != nil {
		return Err[string](__err0)
	}
	b := __v0
	return Ok[string, error](string(b))
}

// DecodeAll parses a stored workspace. Older single-event payloads fail
// here; callers fall back to Decode for migration.
func DecodeAll(s string) Result[map[string]Event, error] {
	var m map[string]Event
	if err := json.Unmarshal([]byte(s), &m); err != nil {
		return Err[map[string]Event](err)
	}
	if m == nil {
		m = map[string]Event{}
	}
	return Ok[map[string]Event, error](m)
}

// FindParticipant looks a participant up by name.
func FindParticipant(e Event, name string) Option[Participant] {
	for _, p := range e.People {
		if p.Name == name {
			return Some(p)
		}
	}
	return None[Participant]()
}

// ParseKey parses a SlotKey back into its grid coordinates; None for
// malformed keys. `?` on an Option short-circuits with None.
func ParseKey(key string) Option[SlotRef] {
	parts := strings.Split(key, ":")
	if len(parts) != 2 {
		return None[SlotRef]()
	}
	__o0 := atoiOpt(parts[0])
	if __o0.IsNone() {
		return None[SlotRef]()
	}
	day := __o0.Unwrap()
	__o1 := atoiOpt(parts[1])
	if __o1.IsNone() {
		return None[SlotRef]()
	}
	slot := __o1.Unwrap()
	return Some(SlotRef{Day: day, Slot: slot})
}

func atoiOpt(s string) Option[int] {
	n, err := strconv.Atoi(s)
	if err != nil {
		return None[int]()
	}
	return Some(n)
}

// Best returns the slot where the most people align, or None when nobody
// has painted any availability yet. Earlier slots win ties.
func Best(e Event) Option[BestSlot] {
	best := BestSlot{Total: len(e.People)}
	for day := 0; day < e.Days; day++ {
		for slot := 0; slot < e.SlotsPerDay(); slot++ {
			key := SlotKey(day, slot)
			if c := e.CountAt(key); c > best.Count {
				best.Key, best.Count = key, c
			}
		}
	}
	if best.Count == 0 {
		return None[BestSlot]()
	}
	return Some(best)
}
